### ISSUE TITLE
Windows errors

### ISSUE THREAD

**Issue by moebiussurfing** [discohead/ofxCrvs#1]
Hey @discohead ,
I just tested to compile your example in Windows/vs 2022/OF 0.12.
Just to report the errors:
![image](https://github.com/discohead/ofxCrvs/assets/2106149/5b2dadbd-6485-4147-807e-b46b924fc88c)

**Comment by discohead** [comment]
Hi @moebiussurfing, I've only just started developing this addon. Also, that example project hasn't been updated for two weeks, quite a bit has changed so it's not really relevant. I don't have a Windows machine (Mac only), but this repo compiles fine for me. Sorry there are no working examples at the moment... I'll get to that eventually!

**Comment by discohead** [comment]
@moebiussurfing The example project actually does compile for me, but I went ahead and removed those `constexpr` variables for now... so if you pull the latest `ofxCrvs` maybe the example will compile now. Just be warned... I'm actively hacking away on this and I'm new to both openFrameworks and C++, so use at your own risk!

**Comment by moebiussurfing** [comment]
cool thanks @discohead ,
do you have any screenshots? I am curious about what these classes are for...

**Comment by discohead** [comment]
@moebiussurfing screenshot of the example project is below. This is a port of a bunch of Java Processing code I wrote. The basic idea is that you create "`FloatOp`'s" (aka `std::function<float(const float)>`) through functional composition, to create complex periodic functions (mostly intended to operate in the [0,1] domain, but not necessarily in all cases) and then you can instantiate a `Crv` with with one of these `FloatOp`'s and produce arrays of points to be drawn or used however you like (at the moment I'm trying to use it with ofxPDSP). Additionally, every `Crv` can have other `Crv`'s that modulate its amplitude, rate, phase and bias, of course those Crvs can have there own modulators and so on... so you can really get carried away! So it's mostly just a tool for generating interesting, modulatable sets of points. A random example...

```
  ofxCrvs::Ops o = ofxCrvs::Ops();
  ofxCrvs::FloatOp op = o.phase(o.sine(o.sine()), o.rate(o.tri(o.sine()), 2.f));
  ofxCrvs::Crv crv = ofxCrvs::Crv(op);
  std::vector<glm::vec3> points = crv.glv3Array(ofGetWidth(), true, true);
  // now points contains a point for every x pixel with the y value from the op above (mapped to screen height by default)
```

`example_ofxCrvs` screenshot:
![image](https://github.com/discohead/ofxCrvs/assets/4748087/fe1c3a38-4d05-4cce-a07a-bb05af64c8ea)

**Comment by moebiussurfing** [comment]
thanks. now is working in Windows too

**Comment by moebiussurfing** [comment]
so do you use that to make audio oscillator waveforms and modulators?

**Comment by discohead** [comment]
I'm using it to generate control data, sequencers and modulators, all of the audio is generated by ofxPDSP.
